### PR TITLE
add binarycat repository

### PR DESCRIPTION
**Pull request by lolbinarycat**
The following points apply when adding a new repository to repos.json

- [x] I ran `./bin/nur format-manifest` after updating `repos.json` (We will use the same script in github actions to make sure we keep the format consistent)
- [x] By including this repository in NUR I give permission to license the
content under the MIT license.

Clarification where license should apply:
The license above does not apply to the packages built by the Nix Packages
collection, merely to the package descriptions (i.e., Nix expressions, build
scripts, etc.). It also might not apply to patches included in Nixpkgs, which
may be derivative works of the packages to which they apply. The aforementioned
artifacts are all covered by the licenses of the respective packages.

### CODE REVIEW

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
Looks like a package is broken:

```
INFO:nur.eval:Evaluate repository binarycat
trace: checking package: /nix/store/rgana4pwlk7m0yaqf9frkwhp7zpl11ad-package.nix
trace: package found: /nix/store/rgana4pwlk7m0yaqf9frkwhp7zpl11ad-package.nix
error:
       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/store/7zjn0ggpaba7mz8a1rydi8g228jwgy8m-source/lib/default.nix:13:12:

           12|   callDir = basePath: extraArgs: mapAttrs
           13|     (name: type:
             |            ^
           14|       let

       … while evaluating call site

       at /nix/store/7zjn0ggpaba7mz8a1rydi8g228jwgy8m-source/lib/default.nix:19:61:

           18|           (if type == "directory" && pathExists pkgPath
           19|            then builtins.trace "package found: ${pkgPath}" (pkgs.callPackage pkgPath extraArgs)
             |                                                             ^
           20|            else {}))

       … while calling 'callPackageWith'

       at /nix/store/nh766jxj8w543n0gmyldkmz2a9k85a5x-source/lib/customisation.nix:153:35:

          152|   */
          153|   callPackageWith = autoArgs: fn: args:
             |                                   ^
          154|     let

       … while evaluating call site

       at /nix/store/nh766jxj8w543n0gmyldkmz2a9k85a5x-source/lib/customisation.nix:205:13:

          204|     in if missingArgs == {}
          205|        then makeOverridable f allArgs
             |             ^
          206|        # This needs to be an abort so it can't be caught with `builtins.tryEval`,

       … while calling anonymous lambda

       at /nix/store/nh766jxj8w543n0gmyldkmz2a9k85a5x-source/lib/customisation.nix:96:17:

           95|     in
           96|     mirrorArgs (origArgs:
             |                 ^
           97|     let

       … while evaluating call site

       at /nix/store/nh766jxj8w543n0gmyldkmz2a9k85a5x-source/lib/customisation.nix:98:16:

           97|     let
           98|       result = f origArgs;
             |                ^
           99|

       … while calling anonymous lambda

       at /nix/store/7zjn0ggpaba7mz8a1rydi8g228jwgy8m-source/pkgs/by-name/jonesforth/package.nix:1:1:

            1| { lib
             | ^
            2| , stdenv

       error: 'writeShellApplication' at /nix/store/nh766jxj8w543n0gmyldkmz2a9k85a5x-source/pkgs/build-support/trivial-builders/default.nix:188:5 called with unexpected argument 'passthru'

       at /nix/store/7zjn0ggpaba7mz8a1rydi8g228jwgy8m-source/pkgs/by-name/jonesforth/package.nix:27:4:

           26|   };
           27| in writeShellApplication {
             |    ^
           28|   name = "jonesforth";
ERROR:nur.update:repository binarycat failed to evaluate: binarycat does not evaluate:
```

**Comment by lolbinarycat** [comment]
should be fixed now

**Comment by lolbinarycat** [comment]
@Mic92 i had to do a force push to make the CI rerun, should actually be fixed now.

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
