### PR TITLE
add rseops repository

### PR DESCRIPTION
**Pull request by vsoch**
The following points apply when adding a new repository to repos.json

- [x] I ran `./bin/nur format-manifest` after updating `repos.json` (We will use the same script in github actions to make sure we keep the format consistent)
- [x] By including this repository in NUR I give permission to license the content under the MIT license.

### CODE REVIEW

**Comment by Mic92** [comment]
bors merge

**Comment by Mic92** [comment]
Can you address the evaluation failure? 

```
INFO:nur.update:Evaluate repository rseops
error: getting status of '/nix/store/mwpsdc01f25jjqxd3jvh9rj7fm9qkmiq-source/pkgs/hpc/akiad': No such file or directory

       … while evaluating 'functionArgs'

       at /nix/store/fz52h1ql10h6dl9lfs77kl5j4wix3z50-source/lib/trivial.nix:440:18:

          439|   */
          440|   functionArgs = f:
             |                  ^
          441|     if f ? __functor

       … from call site

       at /nix/store/fz52h1ql10h6dl9lfs77kl5j4wix3z50-source/lib/customisation.nix:120:15:

          119|       f = if lib.isFunction fn then fn else import fn;
          120|       fargs = lib.functionArgs f;
             |               ^
          121|

       … while evaluating 'filterAttrs'

       at /nix/store/fz52h1ql10h6dl9lfs77kl5j4wix3z50-source/lib/attrsets.nix:224:23:

          223|   */
          224|   filterAttrs = pred: set:
             |                       ^
          225|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));

       … from call site

       at /nix/store/fz52h1ql10h6dl9lfs77kl5j4wix3z50-source/lib/customisation.nix:130:10:

          129|         # Filter out arguments that have a default value
          130|         (lib.filterAttrs (name: value: ! value)
             |          ^
          131|         # Filter out arguments that would be passed

       … while evaluating 'callPackageWith'

       at /nix/store/fz52h1ql10h6dl9lfs77kl5j4wix3z50-source/lib/customisation.nix:117:35:

          116|   */
          117|   callPackageWith = autoArgs: fn: args:
             |                                   ^
          118|     let

       … from call site

       at /nix/store/mwpsdc01f25jjqxd3jvh9rj7fm9qkmiq-source/default.nix:17:11:

           16|
           17|   adiak = pkgs.callPackage ./pkgs/hpc/akiad { };
             |           ^
           18|   caliper = pkgs.callPackage ./pkgs/hpc/caliper { };
```

**Comment by vsoch** [comment]
okay @Mic92 should be fixed!

**Comment by Mic92** [comment]
bors merge

**Comment by vsoch** [comment]
looking into this (sorry didn't know about how these tests work or would be run!)

**Comment by vsoch** [comment]
Huh so these look like errors with other NUR? 

```
ERROR:nur.update:repository jomik failed to evaluate: jomik does not evaluate:
$ nix-env -f /run/user/1001/tmp269o11rm/default.nix -qa * --meta --xml --allowed-uris https://static.rust-lang.org/ --option restrict-eval true --option allow-import-from-derivation true --drv-path --show-trace -I nixpkgs=/nix/store/bd6rjk9k0f06zvsispa5a0j0p5gh1bm0-source -I /nix/store/r09mxdjap6alsfm5yqjla7rl5q6jr40m-source -I /run/user/1001/tmp269o11rm/default.nix -I /home/runner/work/NUR/NUR/lib/evalRepo.nix
remote: Repository not found.
fatal: repository 'https://github.com/JoshuaFern/nur-package-lab/' not found
ERROR:nur.update:Failed to updated repository joshuafern
Traceback (most recent call last):
```
Do you want me to remove them?

**Comment by Mic92** [comment]
We just want to avoid import-from-derivation in NUR. Repos should be self-contained.
If you have other repos with nix expressions you can include them as submodules. If you download source code use `fetchurl` instead of `builtins.fetchTarball`.

**Comment by Mic92** [comment]
bors merge

**Comment by vsoch** [comment]
So just to clarify - I can’t use any nixpkgs here I’d have to copy over the files? That makes things very hard… how do I take advantage of the 80k+ modules that already exist? Can you show me examples or a suggestion to my PR?

**Comment by Mic92** [comment]
> So just to clarify - I can’t use any nixpkgs here I’d have to copy over the files? That makes things very hard… how do I take advantage of the 80k+ modules that already exist? Can you show me examples or a suggestion to my PR?

You get import the nixpkgs copy that gets copied from the user but not vendor your own one.

**Comment by vsoch** [comment]
okay gotcha! So I'm trying to use pkgs instead, but this doesn't seem to work:

```
, withOpenmpi? false, pkgs.openmpi
, withMpich ? false, pkgs.mpich
```
I think because pkgs is imported there. I  can't find any other repos that have this kind of statement - doing a conditional variable based on a package. Do you know how to do it?

**Comment by vsoch** [comment]
okay figured that out! I'm close, just trying to figure out how to import another package in the same repo...
```
error: undefined variable 'adiak'

       at /workspaces/nix/pkgs/hpc/caliper/default.nix:57:43:

           56|
           57|   buildInputs = [ cmake python3 pkgs.papi adiak ] ++
             |                                           ^
           58|     lib.optional libpfmSupport pkgs.libpfm ++
```

**Comment by Mic92** [comment]
This is what I use to reference my own packages: https://github.com/Mic92/nur-packages/blob/664a460d0202b94f2d1a94a43170c7325455ce60/pkgs/python-pkgs/default.nix#L15

**Comment by vsoch** [comment]
I can't figure it out - I probably shouldn't be up at 3:40am but you are awake and I'm so desperate for your help! I'm close, I just can't get that adiak import to work... could you take a look and see if anything pops out? https://github.com/rse-ops/nix/commit/c57cddc4d382ea56f11b360e2b26a979ce2b60ac

**Comment by Mic92** [comment]
See https://github.com/rse-ops/nix/commit/c57cddc4d382ea56f11b360e2b26a979ce2b60ac#r88629456

**Comment by vsoch** [comment]
I'm not added to nix as a maintainer yet, so there might be an issue with maintainers.vsoch. Is there a way to custom define  it, or should I remove for now?

**Comment by vsoch** [comment]
ah maybe I can try this https://github.com/nix-community/nur-combined/blob/4f6584f964482be603e3f5649605af3141ca7ec3/repos/wamserma/default.nix#L12

**Comment by vsoch** [comment]
okay done.

**Comment by vsoch** [comment]
okay I'm not sure that worked:

```
error: attribute 'vsoch' missing

       at /nix/store/z2y7bl598skgh2s4fnn39zn5vamxscbj-source/pkgs/hpc/adiak/default.nix:38:21:

           37|     license = licenses.mit;
           38|     maintainers = [ maintainers.vsoch ];
             |                     ^
           39|     platforms = platforms.linux;

       … while querying the derivation named 'adiak-0.2.2'
```
here is what I did:

https://github.com/rse-ops/nix/blob/2f5107e6a417bbfedcff478a99df40c135241977/default.nix#L16

**Comment by vsoch** [comment]
hey @Mic92 ! Sorry to bother you again,  I am looking forward to using my repo and I think we are close! Locally the only remaining thing (that I don't think I have working yet) is getting maintainers working - see my comment above. Do you have a suggestion for this?

**Comment by Mic92** [comment]
You would need to pass your own maintainers attr set into the build:

https://github.com/rse-ops/nix/blob/2f5107e6a417bbfedcff478a99df40c135241977/pkgs/hpc/adiak/default.nix#L4

And than also here:

https://github.com/rse-ops/nix/blob/2f5107e6a417bbfedcff478a99df40c135241977/default.nix#L18

Otherwise just leave it out for now.

**Comment by vsoch** [comment]
okay let me try this out!

**Comment by vsoch** [comment]
okay I updated my repo : https://github.com/rse-ops/nix/commit/7a63d8f9554468084bf90b128d6e9a588bd1a99e

For some reason my local tests aren't working (sorry) so I think we need to test with bors again.

**Comment by Mic92** [comment]
bors merge

**Comment by vsoch** [comment]
Yay!! :partying_face: Thank you so much for your help @Mic92 !! This is very exciting for me - really looking forward to developing this set of packages.

**Pull request merged**
