### PR TITLE
try to fix build by removing repositories

### PR DESCRIPTION
**Pull request by Mic92**
It actually build fine locally. No idea what is causing this.

### CODE REVIEW

**Comment by ilya-fedin** [comment]
(I have the same errors locally)

**Comment by Mic92** [comment]
@ilya-fedin maybe it's the channel version, what are you using?

**Comment by ilya-fedin** [comment]
@Mic92 
nixpkgs-unstable on arch
nixos-unstable on nixos
Both are affected

**Comment by Mic92** [comment]
@ilya-fedin The errors are fine, but does `nur update` exit with exit code 0?

**Comment by ilya-fedin** [comment]
@Mic92 yes, exit code 0

**Comment by ilya-fedin** [comment]
Maybe the build process is just too long?
изображение

**Comment by Mic92** [comment]
@ilya-fedin Yes, but it seems to be already finished evaluating all repositories and the step that comes after should be pretty simple.

**Comment by ilya-fedin** [comment]
@Mic92 No. Last repository when I ran `nur update` locally was `piensa`. In Travis-CI log - `jomik`.

**Comment by Mic92** [comment]
It actually seems to stuck, when evaluating `krebs` when you look at the latest build log, which added more logging.

**Comment by Mic92** [comment]
It might a network issue, when downloading the krebs repository.

**Pull request merged**
