### PR TITLE
replace language: nix

### PR DESCRIPTION
**Pull request by abathur**
Just testing nix-travis-ci for now.

@Mic92 Can you take a peek at the result here? It passed, but I also see a fair number of red Error messages in the output--are those expected/OK, or does it indicate a problem?

### CODE REVIEW

**Comment by Mic92** [comment]
> Just testing nix-travis-ci for now.
> 
> @Mic92 Can you take a peek at the result here? It passed, but I also see a fair number of red Error messages in the output--are those expected/OK, or does it indicate a problem?

Those errors are fine. It's just all the people that don't care to fix their repositories.

**Comment by abathur** [comment]
Thanks! Not sure how you meant that you'd take it for a test drive, so I've marked this as ready, just-in-case

**Comment by Mic92** [comment]
If something breaks, we still have irc notifications.

**Comment by Mic92** [comment]
Looks like everything worked out: https://github.com/nix-community/NUR/commits/master
We need the same here as well: https://github.com/nix-community/nur-packages-template
This is what our repo maintainer use.

**Pull request merged**
