### PR TITLE
Adding vsoch NUR to list

### PR DESCRIPTION
**Pull request by vsoch**
I'm loving building Nix packages and would like to start my own personal NUR. Thank you!

The following points apply when adding a new repository to repos.json

- [x] I ran `./bin/nur format-manifest` after updating `repos.json` (We will use the same script in github actions to make sure we keep the format consistent)
- [x] By including this repository in NUR I give permission to license the
content under the MIT license.

### CODE REVIEW

**Comment by Mic92** [comment]
bors merge

**Comment by vsoch** [comment]
Is this an error of my doing, or something I can fix?

**Comment by Mic92** [comment]
bors merge

**Comment by Mic92** [comment]
CI error was addressed in https://github.com/nix-community/NUR/commit/a5fbd4623caa89077afd9949c8c969930b8952fb

**Comment by Mic92** [comment]
This error is legit now: https://github.com/nix-community/NUR/actions/runs/3646364482/jobs/6157362068#step:4:541

**Comment by vsoch** [comment]
That’s really strange - I pulled the branch locally and ran the script but didn’t see any changes. I can try again.

**Comment by vsoch** [comment]
Doh, was on the master branch still!

**Comment by vsoch** [comment]
yay!! :green_apple:

**Comment by Mic92** [comment]
bors merge

**Pull request merged**
