### PR TITLE
Add fgaz's repository

### PR DESCRIPTION
**Pull request by fgaz**
- [x] By including this repository in NUR I give permission to license the
content under the MIT license.

Note: The license above does not apply to the packages built by the
Nix Packages collection, merely to the package descriptions (i.e., Nix
expressions, build scripts, etc.).  It also might not apply to patches
included in Nixpkgs, which may be derivative works of the packages to
which they apply. The aforementioned artifacts are all covered by the
licenses of the respective packages.

### CODE REVIEW

**Comment by Mic92** [comment]
I like the structure of your repository. This project could need an example repository, that people can fork from.

**Comment by fgaz** [comment]
Thanks!

I can extract the skeleton and put it in a separate repo, but first I'll have to polish a couple of things

**Comment by fgaz** [comment]
@Mic92 Here is is! https://github.com/fgaz/nur-packages-template

**Comment by Mic92** [comment]
Do you mind, if you fork this repository into the nix-community repository? I can give you access there too.
I have a question regarding cachix: In order to use a binary cache the local nixpkgs channel should be in sync with what travis uses. How do achieve that?

**Comment by fgaz** [comment]
> Do you mind, if you fork this repository into the nix-community repository? I can give you access there too.

Sure

> I have a question regarding cachix: In order to use a binary cache the local nixpkgs channel should be in sync with what travis uses. How do achieve that?

Travis allows you to schedule builds. I set up a weekly build (maybe I should switch it to daily), so most iterations of the unstable channel are covered. Having the channel advancement trigger a build would be ideal, but I have yet to investigate that.

**Pull request merged**
