### PR TITLE
re-add irc notifications

### PR DESCRIPTION
**Pull request by Mic92**
The following points apply when adding a new repository to repos.json

- [ ] I ran `./bin/nur format-manifest` after updating `repos.json` (We will use the same script in travis ci to make sure we keep the format consistent)
- [ ] By including this repository in NUR I give permission to license the
content under the MIT license.

Clarification where license should apply:
The license above does not apply to the packages built by the
Nix Packages collection, merely to the package descriptions (i.e., Nix
expressions, build scripts, etc.).  It also might not apply to patches
included in Nixpkgs, which may be derivative works of the packages to
which they apply. The aforementioned artifacts are all covered by the
licenses of the respective packages.

### CODE REVIEW

**Comment by zimbatm** [comment]
@Mic92 how noisy is it? would it make sense to post the #nix-community channel instead?

**Comment by Mic92** [comment]
Maybe one update per hour on average?

**Comment by Mic92** [comment]
https://logs.nix.samueldr.com/nixos-nur/2020-01-12

**Comment by zimbatm** [comment]
hmm yeah that might be a bit too noisy actually

**Pull request merged**
