### PR TITLE
Flake-ify NUR

### PR DESCRIPTION
**Pull request by Pandapip1**
This has a similar rationale to https://github.com/nix-community/NUR/pull/677

This breaks anything that depends on the previous flake behavior, but should mean that NUR is easier to use and uses the standard flake attributes.

I'll leave this open for at least 48 hours in order to receive feedback before merging.

### CODE REVIEW

**Comment by Pandapip1** [comment]
Moving to draft. There are a few more changes I'd like to make.

**Comment by Pandapip1** [comment]
@mergify queue

**Comment by Shados** [comment]
This appears to have broken NUR's github action Update workflow?

**Comment by Pandapip1** [comment]
Good catch. Looks like it should be an easy fix.

**Pull request merged**
