### PR TITLE
add bandithedoge repo

### PR DESCRIPTION
**Pull request by bandithedoge**
- [x] I ran `./bin/nur format-manifest` after updating `repos.json` (We will use the same script in github actions to make sure we keep the format consistent)
- [x] By including this repository in NUR I give permission to license the
content under the MIT license.

Clarification where license should apply:
The license above does not apply to the packages built by the
Nix Packages collection, merely to the package descriptions (i.e., Nix
expressions, build scripts, etc.).  It also might not apply to patches
included in Nixpkgs, which may be derivative works of the packages to
which they apply. The aforementioned artifacts are all covered by the
licenses of the respective packages.

### CODE REVIEW

**Comment by Mic92** [comment]
Sorry, flakes are not supported here:

```
 $ nix-env -f /tmp/tmp83ml76_g/default.nix -qa * --meta --xml --allowed-uris https://static.rust-lang.org --option restrict-eval true --option allow-import-from-derivation true --drv-path --show-trace -I nixpkgs=/nix/store/2l82f12jkym0xirx2k7dbz5fr7f63vbv-source -I /nix/store/03dad659j70kwxfrh4d0d13cg9f5q2r3-source -I /tmp/tmp83ml76_g/default.nix -I /home/runner/work/NUR/NUR/lib/evalRepo.nix
INFO:nur.update:Evaluate repository bandithedoge
error: access to URI 'https://github.com/edolstra/flake-compat/archive/b7547d3eed6f32d06102ead8991ec52ab0a4f1a7.tar.gz' is forbidden in restricted mode

       … while evaluating the file '/nix/store/qmy8z0kcb7s17z15z3c7f9mwi06pa8qg-nur-packages/pkgs/mpdcord/default.nix':
ERROR:nur.update:repository bandithedoge failed to evaluate: bandithedoge does not evaluate:
```

You can specify an alternative file to import nur packages from.

**Comment by bandithedoge** [comment]
I changed it to use `default.nix`.

**Comment by Mic92** [comment]
Looks like it's still the same issue.

**Comment by Mic92** [comment]
But other file this time:

$ nix-env -f /tmp/tmp_d72650k/default.nix -qa * --meta --xml --allowed-uris https://static.rust-lang.org --option restrict-eval true --option allow-import-from-derivation true --drv-path --show-trace -I nixpkgs=/nix/store/br9jwb9daldmw2sii3q9am94i2m8nwi7-source -I /nix/store/03dad659j70kwxfrh4d0d13cg9f5q2r3-source -I /tmp/tmp_d72650k/default.nix -I /home/runner/work/NUR/NUR/lib/evalRepo.nix
INFO:nur.update:Evaluate repository bandithedoge
error: access to URI 'https://github.com/edolstra/flake-compat/archive/b7547d3eed6f32d06102ead8991ec52ab0a4f1a7.tar.gz' is forbidden in restricted mode

       … while evaluating the file '/nix/store/qmy8z0kcb7s17z15z3c7f9mwi06pa8qg-nur-packages/pkgs/mpdcord/default.nix':

**Comment by bandithedoge** [comment]
I think the issue is that the `mpdcord` derivation imports flake-compat from `flake.lock`. I'm going to push a fix for that.

**Comment by Mic92** [comment]
Ok. I am re-running ci.

**Comment by Mic92** [comment]
moved to draft mode until this is fixed.

**Comment by Mic92** [comment]
Please reopen if you still want to add your repo and evaluation fixed.

**Comment by bandithedoge** [comment]
I fixed my repo but I can't reopen the PR myself.

**Pull request closed without merging**
