### PR TITLE
Add submodule attribute to mpickering

### PR DESCRIPTION
**Pull request by mpickering**
This wasn't added in the origin PR.

### CODE REVIEW

**Comment by makefu** [comment]
seems like the pretty printer is super now super picky about the sorting of keys and demands "**s**ubmodule" ahead of "**u**rl"

**Comment by mpickering** [comment]
I changed the order now.

**Comment by Mic92** [comment]
Thanks!

**Comment by Mic92** [comment]
I just noticed that changes like this should also update `repos.json.lock` in the same pull request.
Will hopefully fixed in future by https://github.com/nix-community/NUR/issues/42

**Comment by Mic92** [comment]
At the moment travis is reasonably fast: https://github.com/nix-community/NUR/commit/2dabb257072d9d0bcdc204325fcd2df6640b0812

**Pull request merged**
