### PR TITLE
add Dev380 repository

### PR DESCRIPTION
**Pull request by Dev380**
The following points apply when adding a new repository to repos.json

- [x] I ran `./bin/nur format-manifest` after updating `repos.json` (We will use the same script in github actions to make sure we keep the format consistent)
- [x] By including this repository in NUR I give permission to license the
content under the MIT license.

Clarification where license should apply:
The license above does not apply to the packages built by the Nix Packages
collection, merely to the package descriptions (i.e., Nix expressions, build
scripts, etc.). It also might not apply to patches included in Nixpkgs, which
may be derivative works of the packages to which they apply. The aforementioned
artifacts are all covered by the licenses of the respective packages.

### CODE REVIEW

**Comment by Dev380** [comment]
CI passes now that I've removed a package that depends on an overlay from a flake input; I'm assuming I need to tweak my CI like this repo did? https://github.com/nix-community/nur-combined/tree/f7a814854548f8cba30e8f2258d1d4d45f78e830/repos/cryolitia

**Comment by Pandapip1** [comment]
Right now, NUR is _not_ flake-centric, and uses the package's default.nix. Therefore, for the time being, you'll need to pull rust-overlay either in your default.nix. Alternatively, consider using nixpkgs' built-in rust tooling.

**Comment by Dev380** [comment]
I followed the second suggestion and switched to the regular nixpkgs.rustPlatform. [Github actions buillds now](https://github.com/Dev380/nur-repo/actions/runs/12272457548) I think, but only since I changed from nixpkgs-unstable to nixos-unstable (for some reason the wisdom-tree python package only builds on the later). Do I have to mark it as only working on nixos-unstable somehow or is it fine as-is?

**Comment by Pandapip1** [comment]
> Do I have to mark it as only working on nixos-unstable somehow or is it fine as-is?

I believe it's fine as-is. I'd recommend you submit a build failure issue to nixpkgs; that kind of report is greatly appreciated, as you probably won't be the only one that's affected!

**Comment by Dev380** [comment]
Strangely enough, the latest nixpkgs-unstable works again. Maybe there was just a temporary issue on that nixos-unstable didn't get yet :shrug:

**Comment by Dev380** [comment]
Is there anything else I need to fix in my nur repo before it's merged?

**Comment by Pandapip1** [comment]
Nope!

@mergify queue

**Comment by Dev380** [comment]
Did mergify not see your comment?

**Comment by Pandapip1** [comment]
Yea, looks like it didn't trigger.

**Comment by Pandapip1** [comment]
Nope!

@mergify queue

**Comment by Pandapip1** [comment]
@mergify queue

**Pull request merged**
