### PR TITLE
add eeva's repository

### PR DESCRIPTION
**Pull request by jpotier**
- [x] By including this repository in NUR I give permission to license the content under the MIT license.

Note: The license above does not apply to the packages built by the Nix Packages collection, merely to the package descriptions (i.e., Nix expressions, build scripts, etc.). It also might not apply to patches included in Nixpkgs, which may be derivative works of the packages to which they apply. The aforementioned artifacts are all covered by the licenses of the respective packages.

### CODE REVIEW

**Comment by Mic92** [comment]
Cool, you have received the first contributor batch!

**Comment by jpotier** [comment]
Yey, and Travis is angry at me :joy_cat:

**Comment by Mic92** [comment]
Do not worry about that. Apparently secrets are not available in pull requests, which makes perfect sense. I will fix that later. Do you mind putting your repository under the MIT license? It would be cool to have single license for NUR.

**Comment by Mic92** [comment]
I added this now as a pull request: https://github.com/nix-community/NUR/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by jpotier** [comment]
Sure, changing that now

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
