### PR TITLE
Add darkkirb repository

### PR DESCRIPTION
**Pull request by DarkKirb**
This repository currently contains the following packages:

- Akkoma, and its pleroma and admin frontends, built from git, with patches for my personal instance
- matrix-media-repo built from git
- git versions of mautrix-signal and mautrix-telegram
- mautrix-discord and mautrix-whatsapp, also built from git
- a usually more updated version of papermc
- Plover with https://github.com/openstenoproject/plover/pull/1461#issuecomment-1065494960 applied (wayland support)
- a few plover plugins, latest pypi version
- KreativeKorp’s fonts
- Emoji for akkoma made by volpeon (https://volpeon.ink/)

The following points apply when adding a new repository to repos.json

- [x] I ran `./bin/nur format-manifest` after updating `repos.json` (We will use the same script in github actions to make sure we keep the format consistent)
- [x] By including this repository in NUR I give permission to license the
content under the MIT license.

Clarification where license should apply:
The license above does not apply to the packages built by the Nix Packages
collection, merely to the package descriptions (i.e., Nix expressions, build
scripts, etc.). It also might not apply to patches included in Nixpkgs, which
may be derivative works of the packages to which they apply. The aforementioned
artifacts are all covered by the licenses of the respective packages.

### CODE REVIEW

**Comment by Mic92** [comment]
bors merge

**Comment by DarkKirb** [comment]
Interesting. Is omitting packageJson in mkYarnPackage, even though i am providing a yarn.nix, an IFD? i think it should be fixed now anyhow

**Comment by Mic92** [comment]
bors merge

**Comment by Mic92** [comment]
bors merge

**Comment by DarkKirb** [comment]
i don’t know why the tests won’t run. hydra has no issues evaluating it, although there is an import from derivation in mkYarnPackage still, which i do not see. closing for now

**Comment by Mic92** [comment]
If you know what needs to change in our check script, you can provide a fix.

**Comment by DarkKirb** [comment]
it seems that nix is ignoring the allow-imports-from-derivation setting? at least for builtins.readFile

i found out why the IFD happens though (i wrote packageJSON as packageJson) and i  pushed a fix

**Comment by Mic92** [comment]
bors merge

**Comment by Mic92** [comment]
finally.

**Pull request merged**
