### PR TITLE
add dagger repository

### PR DESCRIPTION
**Pull request by sagikazarmark**
The following points apply when adding a new repository to repos.json

- [x] I ran `./bin/nur format-manifest` after updating `repos.json` (We will use the same script in github actions to make sure we keep the format consistent)
- [x] By including this repository in NUR I give permission to license the
content under the MIT license.

Clarification where license should apply:
The license above does not apply to the packages built by the Nix Packages
collection, merely to the package descriptions (i.e., Nix expressions, build
scripts, etc.). It also might not apply to patches included in Nixpkgs, which
may be derivative works of the packages to which they apply. The aforementioned
artifacts are all covered by the licenses of the respective packages.

---

For reference: https://github.com/NixOS/nixpkgs/issues/260848

### CODE REVIEW

**Comment by Mic92** [comment]
I guess the apache license is also fine (afaik compatible to MIT).

**Comment by sagikazarmark** [comment]
@Mic92 thanks for the quick reply. I'm talking to the Dagger folks to figure out if they want to keep Apache 2.0 which is why I kept it a draft for now.

Tagging @gerhard

Either works for me. If Apache 2.0 is fine, I'll mark it as ready and we are done.

**Comment by sagikazarmark** [comment]
The decision has been made to revert license to MIT. This PR is good to go.

Thank you all!

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
