### PR TITLE
Add mpickering nur-packages repo

### PR DESCRIPTION
**Pull request by mpickering**
- [x] By including this repository in NUR I give permission to license the
content under the MIT license.

Note: The license above does not apply to the packages built by the
Nix Packages collection, merely to the package descriptions (i.e., Nix
expressions, build scripts, etc.).  It also might not apply to patches
included in Nixpkgs, which may be derivative works of the packages to
which they apply. The aforementioned artifacts are all covered by the
licenses of the respective packages.

### CODE REVIEW

**Comment by Mic92** [comment]
It is now possible to specify a different `file` when adding a repository. Do you think it make sense to add `https://github.com/mpickering/haskell-nix-plugin` directly instead?

**Comment by mpickering** [comment]
I would prefer to do it this way so it's easier for me to add other packages in future?

**Comment by Mic92** [comment]
In https://github.com/nix-community/NUR/pull/16 I want to restrict evaluation because of the security risk when evaluating nix code. Would be `git submodule` support for repos an acceptable solution to load https://github.com/mpickering/haskell-nix-plugin in the nur-packages repository?

**Comment by mpickering** [comment]
So you are suggesting I add `haskell-nix-plugin` as a submodule in my `nur-packages` repo to avoid using `fetchgit`?

**Comment by mpickering** [comment]
That will still be a bit annoying as when I update `haskell-nix-plugin`, I will also have to update the hash that `nur-packages` points to.

**Comment by mpickering** [comment]
I added it as a submodule now, is that better?

**Comment by Mic92** [comment]
Almost, just replace in https://github.com/mpickering/nur-packages/blob/master/haskell-plugins/default.nix
Otherwise the import will not work.

```diff
- import "./haskell-nix-plugin/overlay.nix"
+ import ./haskell-nix-plugin/overlay.nix
```

**Comment by Mic92** [comment]
I will merge this after https://github.com/nix-community/NUR/pull/18 is merged, which in turn needs https://github.com/NixOS/nixpkgs/commit/cb2862e214dc9245a61bc4d3242f895ac969ffa5 to land in nixpkgs unstable (when hydra is finished).

**Pull request merged**
