### PR TITLE
add eownerdead repository

### PR DESCRIPTION
**Pull request by eownerdead**
The following points apply when adding a new repository to repos.json

- [x] I ran `./bin/nur format-manifest` after updating `repos.json` (We will use the same script in github actions to make sure we keep the format consistent)
- [x] By including this repository in NUR I give permission to license the
content under the MIT license.

Clarification where license should apply:
The license above does not apply to the packages built by the Nix Packages
collection, merely to the package descriptions (i.e., Nix expressions, build
scripts, etc.). It also might not apply to patches included in Nixpkgs, which
may be derivative works of the packages to which they apply. The aforementioned
artifacts are all covered by the licenses of the respective packages.

### CODE REVIEW

**Comment by eownerdead** [comment]
Sorry. I misread the document totally...

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
I think you forgot to commit a file?

```
INFO:nur.eval:Evaluate repository eownerdead
error:
       … while evaluating the file '/home/runner/work/_temp/tmpnl_744m9/default.nix':

       … while evaluating call site

       at /home/runner/work/_temp/tmpnl_744m9/default.nix:3:1:

            2|                     with import <nixpkgs> {};
            3| import /home/runner/work/NUR/NUR/lib/evalRepo.nix {
             | ^
            4|   name = "eownerdead";

       … while calling anonymous lambda

       at /home/runner/work/NUR/NUR/lib/evalRepo.nix:1:1:

            1| { name
             | ^
            2| , url

       … while realising the context of path '/nix/store/3i6dmjkwvrijk1i8nhzri6nbzaamn5i3-flakes/default.nix'

       at /home/runner/work/NUR/NUR/lib/evalRepo.nix:25:10:

           24|
           25|   expr = import src;
             |          ^
           26|   args = builtins.functionArgs expr;

       error: getting status of '/nix/store/3i6dmjkwvrijk1i8nhzri6nbzaamn5i3-flakes/default.nix': No such file or directory
```

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@mergify refresh

**Comment by Mic92** [comment]
@mergify queue

**Comment by eownerdead** [comment]
```
       at /nix/store/h987xd12z7kwgx4nscrqrvk9gr1x8ilj-flakes/default.nix:2:1:

            1| # Packages for NUR
            2| { flake ? builtins.getFlake ("git+file://" + toString ./.)
             | ^
            3| , pkgs ? flake.inputs.nixpkgs { } }:

       … while fetching the input 'git+file:///nix/store/h987xd12z7kwgx4nscrqrvk9gr1x8ilj-flakes'

       error: program 'git' failed with exit code 128
```
Oops, it requires git! I checked evaluation locally, though😥
I've fixed and tested in docker. It must work now!

**Comment by Mic92** [comment]
@mergify queue

**Comment by eownerdead** [comment]
Maybe we need to rerun the tests.

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@mergify refresh

**Comment by Mic92** [comment]
@mergify rebase

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
