### PR TITLE
add kugland repository

### PR DESCRIPTION
**Pull request by kugland**
The following points apply when adding a new repository to repos.json

- [x] I ran `./bin/nur format-manifest` after updating `repos.json` (We will use the same script in github actions to make sure we keep the format consistent)
- [x] By including this repository in NUR I give permission to license the
content under the MIT license.

Clarification where license should apply:
The license above does not apply to the packages built by the Nix Packages
collection, merely to the package descriptions (i.e., Nix expressions, build
scripts, etc.). It also might not apply to patches included in Nixpkgs, which
may be derivative works of the packages to which they apply. The aforementioned
artifacts are all covered by the licenses of the respective packages.

### CODE REVIEW

**Comment by Mic92** [comment]
Looks like some import-from-derivation going on here:

```
INFO:nur.eval:Evaluate repository kugland
error:
       … while querying the derivation named 'neocities-deploy-0.1.11'

       … while evaluating the attribute 'cargoDeps' of the derivation 'neocities-deploy-0.1.11'

       at /nix/store/1dnrk528jzs1k3aqyg3n1irsfang7axq-source/pkgs/stdenv/generic/make-derivation.nix:353:7:

          352|     // (optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          353|       name =
             |       ^
          354|         let

       … while evaluating the attribute 'buildCommand' of the derivation 'cargo-vendor-dir'

       at /nix/store/1dnrk528jzs1k3aqyg3n1irsfang7axq-source/pkgs/stdenv/generic/make-derivation.nix:353:7:

          352|     // (optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          353|       name =
             |       ^
          354|         let

       … while realising the context of path '/nix/store/53whyhphnggwb8vrlsi43cv5mqav1pv3-source/Cargo.lock'

       at /nix/store/1dnrk528jzs1k3aqyg3n1irsfang7axq-source/pkgs/build-support/rust/import-cargo-lock.nix:45:10:

           44|     if lockFile != null
           45|     then builtins.readFile lockFile
             |          ^
           46|     else args.lockFileContents;

       error: path '/nix/store/7jb0bq7vk5anlsqcmk2f813idjg6k5y8-source.drv' is not valid
ERROR:nur.update:repository kugland failed to evaluate: kugland does not evaluate:
```

**Comment by kugland** [comment]
@Mic92 

> Looks like some import-from-derivation going on here:
>
> [...]
> 
>        … while evaluating the attribute 'cargoDeps' of the derivation 'neocities-deploy-0.1.11'

I was using the attribute `cargoDeps` for this derivation, but I replaced it with the explicit `cargoSha256`, so I think this error should be gone now.

How can I force a new check? I mean, this pull request includes only the addition of my repo to `repos.json`, and there’s nothing to change here.

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@mergify refresh

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@mergify rebase

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
