### PR TITLE
add manveru repository

### PR DESCRIPTION
**Pull request by manveru**
- [x] By including this repository in NUR I give permission to license the
content under the MIT license.

Note: The license above does not apply to the packages built by the
Nix Packages collection, merely to the package descriptions (i.e., Nix
expressions, build scripts, etc.).  It also might not apply to patches
included in Nixpkgs, which may be derivative works of the packages to
which they apply. The aforementioned artifacts are all covered by the
licenses of the respective packages.

### CODE REVIEW

**Comment by Mic92** [comment]
Our format script is a bit nit picky when it comes to the format of the json file.

**Comment by Infinisil** [comment]
Maybe the update script could run the format script as well?

**Comment by Infinisil** [comment]
Maybe the update script could run the format script as well?

**Comment by Mic92** [comment]
It might be that our evaluation test is too strict: https://github.com/nix-community/NUR/blob/master/nur/update.py#L184
However I don't know why.

**Comment by manveru** [comment]
Yeah, was already wondering whether IFD would work or not.

**Comment by manveru** [comment]
It'd need `--option allow-import-from-derivation true` for this I think. If that was possible, I could package a bunch of JS applications without much effort.

**Comment by Mic92** [comment]
Does `allow-import-from-derivation` involve network access? 
My reasoning between restrict-eval is the following case: https://github.com/nix-community/NUR/pull/16#issue-198527982

**Comment by Mic92** [comment]
Also safe evaluation would still require a sandbox because `builtins.getEnv "GITHUB_OAUTH_TOKEN"` also could become a problem.

**Comment by Mic92** [comment]
@manveru do you know why yarn2nix tries to download from github during the evaluation phase?

**Comment by Mic92** [comment]
Ah I oversaw that `fetchGit` was used without providing a checksum.

**Comment by Mic92** [comment]
It seems that `allow-import-from-derivation` is not able to download external content, when `restrict-eval` is used, so the impact on evaluation time should be reasonable and the result reproducible in most cases.

**Comment by Mic92** [comment]
I opened a ticket for that.

**Pull request closed without merging**
