### PR TITLE
nur: Update python side of GitLab URL parsing

### PR DESCRIPTION
**Pull request by tilpner**

### CODE REVIEW

**Comment by tilpner** [comment]
@Mic92 lint.sh seems to want me to format something, but it doesn't tell me what. If it means the lines that are longer than 80 chars, they are long in master too.

**Comment by Mic92** [comment]
@tilpner This can be fixed by using [black](https://github.com/ambv/black)

**Comment by tilpner** [comment]
Oh, so lint.sh was added after prefetch.py, and it never had to go through linting?
Travis seems fine now.

**Comment by Mic92** [comment]
No, the reformat was also in those lines that where changed.

**Pull request merged**
